services:
  - type: web
    name: okami-bot
    runtime: node
    plan: free
    region: ohio
    buildCommand: pnpm install
    startCommand: pnpm start
    healthCheckPath: /status
    envVars:
      - key: DATA_DIR
        value: ./data
      - key: ADMIN_PASSWORD
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: FB_PAGE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: NODE_VERSION
        value: 22.13.0
    disk:
      name: okami-data
      mountPath: /home/render/project/src/data
      sizeGB: 1
